import com.oaknorth.drools.RatioValue;
import com.oaknorth.drools.Record;

//from row number: 1
rule "Row 1 fr-adjusted-gross-leverage-drl"
	dialect "mvel"
	when
		$record : Record( ratioName == "Adjusted Gross Leverage",  $ratioValueList : ratioValues)
		ratioValue : RatioValue( data >= 0.0 , data < 3.5) from $ratioValueList
	
	then
	    //ratioValue.setAbsoluteAnomaly(0);
	
		modify( record ) {
				setRatioValues($ratioValueList);
		}
end