import com.oaknorth.drools.RatioValue;
import com.oaknorth.drools.Record;

//from row number: 1
rule "Row 1 calculate absolute anomaly"
	dialect "mvel"
	no-loop
	lock-on-active
	when
		$record : Record( ratioName == "Adjusted Gross Leverage",  $ratioValueList : ratioValues)
		ratioValue : RatioValue( data >= 0.0 , data < 3.5) from $ratioValueList
	
	then
	    ratioValue.setAbsoluteAnomaly(0);
        update($record);
end

//from row number: 1
rule "Row 2 calculate absolute anomaly"
	dialect "mvel"
	no-loop
	lock-on-active
	when
		$record : Record( ratioName == "Adjusted Gross Leverage",  $ratioValueList : ratioValues)
		ratioValue : RatioValue( data >= 3.5 , data < 4.0) from $ratioValueList
	
	then
	    ratioValue.setAbsoluteAnomaly(1);
        update($record);
end

//from row number: 1
rule "Row 3 calculate absolute anomaly"
	dialect "mvel"
	no-loop
	lock-on-active
	when
		$record : Record( ratioName == "Adjusted Gross Leverage",  $ratioValueList : ratioValues)
		ratioValue : RatioValue( data >= 4.0 , data < 10000) from $ratioValueList
	
	then
	    ratioValue.setAbsoluteAnomaly(2);
        update($record);
end

//from row number: 1
rule "Row 1 calculate absolute anomaly of last year"
	dialect "mvel"
	no-loop
	lock-on-active
	when
		$record : Record( ratioName == "Adjusted Gross Leverage",  (ratioValues.get(ratioValues.size() - 1).getAbsoluteAnomaly() == 0))
	
	then
    	$record.getAnomaly().add(1);
	   update($record);
end

//from row number: 1
rule "Row 2 calculate absolute anomaly of last year"
	dialect "mvel"
	no-loop
	lock-on-active
	when
		$record : Record( ratioName == "Adjusted Gross Leverage",  (ratioValues.get(ratioValues.size() - 1).getAbsoluteAnomaly() == 0))
	
	then
    	$record.getAnomaly().add(0);
	   update($record);
end