import com.oaknorth.drools.Record;
import com.oaknorth.drools.RatioValue;

rule "rule 1 calculate absolute majority anomaly"
    when
        record : Record(ratioName == "Adjusted Gross Leverage", $ratioValueList: ratioValues)
        $total : Number() from accumulate(
         RatioValue( $p : absoluteAnomaly ) from $ratioValueList,
         sum( $p ) )
        ($total > 1.0) 
    then
        modify(record){
            set(absoluteMajorityAnomaly(1))
        }
end

rule "rule 2 calculate absolute majority anomaly"
    when
        record : Record(ratioName == "Adjusted Gross Leverage", $ratioValueList: ratioValues)
        $total : Number() from accumulate(
         RatioValue( $p : absoluteAnomaly ) from $ratioValueList,
         sum( $p ) )
        ($total < 1.0) 
    then
        modify(record){
            set(absoluteMajorityAnomaly(0))
        }
end
