import com.oaknorth.drools.Record;
import com.oaknorth.drools.RatioValue;

rule "calculate slope"
    when
        record : Record(ratioName == "Adjusted Gross Leverage")
    then
        RatioValue ratioValue0 = record.getRatioValues().get(0);
        RatioValue ratioValue1 = record.getRatioValues().get(1);
        RatioValue ratioValue2 = record.getRatioValues().get(2);
        
        modify(record){
            record.getRatioValues().get(2).setSlope((ratioValue2.getData() - ratioValue0.getData()) / 2.0 );
        }
end        