import com.oaknorth.drools.Record;
import com.oaknorth.drools.RatioValue;

rule "rule 1 calculate absolute majority anomaly"
lock-on-active
    when
        finance : FinanceData($recordList : records)
        record : Record(ratioName == "Adjusted Gross Leverage", $ratioValueList: ratioValues) from $recordList
        $total : Number(doubleValue > 1) from accumulate(
         RatioValue( $p : absoluteAnomaly ) from $ratioValueList,
         sum( $p ) )
    then
        modify(record){
            setAbsoluteMajorityAnomaly(1);
        }
end

rule "rule 2 calculate absolute majority anomaly"
lock-on-active
    when
        finance : FinanceData($recordList : records)
        record : Record(ratioName == "Adjusted Gross Leverage", $ratioValueList: ratioValues) from $recordList
        $total : Number(doubleValue <= 1) from accumulate(
         RatioValue( $p : absoluteAnomaly ) from $ratioValueList,
         sum( $p ) )
    then
        modify(record){
            setAbsoluteMajorityAnomaly(0);
        }
end
