package com.oaknorth.drools;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class FinanceData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "FINANCEDATA_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "FINANCEDATA_ID_GENERATOR", sequenceName = "FINANCEDATA_ID_SEQ")
    private java.lang.Long id;

    public FinanceData() {
    }
    
    public FinanceData(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}