package com.oaknorth.drools;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class RatioValues implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "RATIOVALUES_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "RATIOVALUES_ID_GENERATOR", sequenceName = "RATIOVALUES_ID_SEQ")
    private java.lang.Long id;

    public RatioValues() {
    }
    
    public RatioValues(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}